import gen_quizzes
import random

mixed_questions = [
    # Cross-Signal & Mixed Concepts
    {"question": "Trong AIOps, khi một metric báo 'latency tăng', dữ liệu nào sẽ giúp xác định 'tại sao'?", "options": ["CPU Metrics", "Network Throughput", "Unstructured Log và Structured Log", "Memory Usage"], "answer": 2, "difficulty": "hard"},
    {"question": "Trong workflow Cross-Signal Analysis, bước nào được thực hiện NGAY SAU khi metric anomaly detector trigger?", "options": ["Train lại mô hình Isolation Forest", "Filter log trong time window (±5 phút) xung quanh điểm anomaly", "Đếm số lượng template unique trong ngày", "Lấy toàn bộ 1TB log ra để parse"], "answer": 1, "difficulty": "hard"},
    {"question": "Lợi ích cốt lõi của việc kết hợp Metric Anomaly Detection và Log Parsing là gì?", "options": ["Nén dung lượng lưu trữ log xuống 50%", "Thu hẹp root cause nhanh gấp nhiều lần bằng cách tìm log template spike cùng thời điểm", "Giảm số lượng CPU tiêu thụ", "Thay thế hoàn toàn con người trong việc sửa lỗi code"], "answer": 1, "difficulty": "hard"},
    {"question": "Giả sử Isolation Forest phát hiện anomaly trên cụm metric (CPU, Memory, Latency), bước tiếp theo tối ưu nhất để debug là gì?", "options": ["Reboot server", "Khởi chạy hàm TfidfVectorizer trên metric", "Lấy thời điểm anomaly để filter log, parse log bằng Drain3 và tìm new template hoặc template spike", "Bỏ qua vì IF hay cho False Positives"], "answer": 2, "difficulty": "hard"},

    # Metric Anomaly - Advanced
    {"question": "Trong kịch bản memory leak (CPU không đổi, Memory tăng, GC Pause tăng), tại sao phương pháp Rolling Z-score (3σ) đơn biến lại thất bại ở giai đoạn đầu?", "options": ["Do Z-score bị lỗi chia cho 0", "Vì mức tăng quá nhỏ (drift) nên rolling mean trượt theo, khiến dữ liệu mới luôn nằm trong ngưỡng 3σ", "Vì Z-score không hỗ trợ tính toán CPU", "Do phân phối của Memory bị right-skewed"], "answer": 1, "difficulty": "hard"},
    {"question": "Isolation Forest (IF) phát hiện memory leak tốt hơn 3σ bằng cách nào?", "options": ["Bằng cách tự động tăng α lên 0.9", "Bằng cách tìm ra correlation bất thường giữa nhiều metric cùng lúc (như Memory tăng nhưng CPU đứng yên)", "Nhờ tốc độ chạy O(1)", "Bằng cách chuyển sang dạng chuỗi thời gian (LSTM)"], "answer": 1, "difficulty": "hard"},
    {"question": "Khi áp dụng EWMA cho memory leak, tại sao ta lại thiết lập giá trị α (alpha) rất nhỏ (VD: 0.05 - 0.1)?", "options": ["Để model nhớ xa hơn trong quá khứ, giúp phát hiện ra drift chậm", "Để tiết kiệm năng lượng tính toán", "Để phản ứng cực nhanh với spike đột ngột", "Vì alpha nhỏ giúp ngăn ngừa Overfitting"], "answer": 0, "difficulty": "hard"},
    {"question": "Nếu metric request latency bị right-skewed mạnh, ta nên sử dụng kỹ thuật nào trước khi áp dụng Z-score?", "options": ["Dùng Isolation Forest đa biến", "Dùng hàm log transform (np.log1p) để nén giá trị lớn, kéo dữ liệu về gần phân phối chuẩn", "Chỉ lấy phần dư (Residual) từ chuỗi", "Xóa toàn bộ các latency lớn hơn mean"], "answer": 1, "difficulty": "hard"},
    {"question": "Tham số `robust=True` trong STL Decomposition giải quyết vấn đề gì?", "options": ["Tránh lỗi OutOfMemory", "Sử dụng iterative reweighting để giảm trọng số của outlier, ngăn chặn outlier làm méo mó trend và 'giấu' anomaly trong residual", "Ép mô hình chạy bằng GPU", "Tự động phát hiện period của seasonal"], "answer": 1, "difficulty": "hard"},
    {"question": "Nếu ta có dữ liệu 1-minute với weekly pattern, giá trị `period` nào sau đây là chính xác nhất cho thuật toán STL?", "options": ["1440", "10080", "168", "288"], "answer": 1, "difficulty": "hard"},
    {"question": "Tại sao việc dùng nguyên giá trị (raw value) để feed vào Isolation Forest thường không hiệu quả trong time series?", "options": ["Vì IF chỉ nhận vector 2 chiều", "Vì IF xem xét từng row độc lập và không hiểu bối cảnh (context) trước đó. Cần tạo các temporal feature (rolling, lag, diff).", "Vì IF cần dữ liệu sạch hoàn toàn", "Vì IF chỉ chạy trên text (log)"], "answer": 1, "difficulty": "hard"},
    {"question": "Tham số `contamination` trong Isolation Forest có ý nghĩa gì và điều chỉnh như thế nào?", "options": ["Là tỷ lệ nhiễu, nếu alert quá nhiều false alarm thì cần giảm xuống (vd: 0.005)", "Là độ sâu của cây, càng sâu càng tốt", "Là số lượng cây, mặc định là 200", "Là tỷ lệ log được lấy mẫu (sampling rate)"], "answer": 0, "difficulty": "hard"},
    {"question": "Điểm ưu việt của One-Class SVM so với Isolation Forest là gì?", "options": ["Chạy nhanh hơn gấp 100x", "Vẽ boundary cực kì chính xác, thích hợp khi có một bộ data 'sạch' (chỉ chứa normal) và dung lượng nhỏ", "Không cần tuning tham số", "Dùng ít RAM hơn"], "answer": 1, "difficulty": "hard"},
    {"question": "Autoencoder phát hiện anomaly như thế nào?", "options": ["Tính độ sâu của nút trên parse tree", "Thông qua Reconstruction Error: mô hình nén và giải nén dữ liệu, nếu là pattern chưa từng thấy thì error sẽ rất cao", "Đo lường Z-score của latent space", "Dùng khoảng cách TF-IDF"], "answer": 1, "difficulty": "hard"},
    {"question": "Trong AIOps, tại sao Recall thường được ưu tiên cao hơn Precision khi xét ngưỡng anomaly?", "options": ["Vì false alarm gây thiệt hại tiền bạc", "Vì bỏ sót anomaly thật (miss) sẽ gây ra outage, SLA breach và thiệt hại khổng lồ. False alarm chỉ tốn 5 phút để check.", "Vì công thức Recall dễ tính hơn", "Vì sếp thích chỉ số Recall"], "answer": 1, "difficulty": "hard"},
    {"question": "Khi hai mô hình anomaly có P và R khác nhau, số đo nào giúp so sánh tổng quan nhất?", "options": ["TTD (Time-to-Detect)", "False Alarm Rate", "F1 Score (Harmonic mean của Precision và Recall)", "Accuracy"], "answer": 2, "difficulty": "hard"},
    {"question": "Sự khác biệt giữa Time-to-Detect (TTD) và Mean-Time-To-Resolve (MTTR) là gì?", "options": ["TTD là thời gian giải quyết sự cố, MTTR là thời gian model phát hiện", "TTD là thời gian từ khi sự cố xảy ra đến khi model alert, detect sớm giúp rút ngắn MTTR", "Hai khái niệm là một", "TTD áp dụng cho metric, MTTR áp dụng cho log"], "answer": 1, "difficulty": "hard"},

    # Log Parsing - Advanced
    {"question": "Tại sao lệnh `grep` lại thất bại trong việc thống kê các lỗi 'Connection timeout' trong môi trường production lớn?", "options": ["Vì grep không hiểu Regex", "Vì các log line khác nhau ở tham số động (IP, port, traceID) nên grep không thể nhóm (cluster) chúng thành template đếm một cách hệ thống", "Vì grep không chạy được trên file > 10GB", "Grep chỉ tìm được chữ in hoa"], "answer": 1, "difficulty": "hard"},
    {"question": "Cấu trúc dữ liệu nào làm nên tốc độ O(1) thần tốc của Drain3?", "options": ["Hash Map", "Fixed-depth parse tree kết hợp heuristic (độ dài, ký tự đầu)", "Linked List", "Graph Neural Network"], "answer": 1, "difficulty": "hard"},
    {"question": "Trong cây phân rã (parse tree) của Drain3, level 1 đóng vai trò gì?", "options": ["Nhóm log theo First Token (thường là Log level)", "Nhóm log theo Similarity", "Nhóm log theo Log length (số lượng từ), vì các log khác chiều dài hiếm khi chung template", "Nhóm log theo Kubernetes Pod"], "answer": 2, "difficulty": "hard"},
    {"question": "Nếu đặt tham số `drain_sim_th` trong Drain3 quá thấp (vd: 0.1), hậu quả trên hệ thống phân tích log là gì?", "options": ["Nó sẽ văng lỗi Out of bounds", "Gộp quá aggressive (quá mức), khiến các lỗi khác nhau bị gộp chung thành 1 template, làm mất thông tin", "Tách ra hàng triệu template vô dụng", "Tốc độ parse chậm đi đáng kể"], "answer": 1, "difficulty": "hard"},
    {"question": "LLM-based Parser cho độ chính xác cực cao về mặt Semantic. Tại sao thực tế enterprise chưa dùng hoàn toàn?", "options": ["Vì nó không hiểu được tiếng Anh", "Vì nó không hỗ trợ API", "Tốc độ rất chậm (hàng trăm ms cho 1 API) và chi phí cực đắt không thể đáp ứng Scale TB/ngày", "Vì kết quả của nó không có định dạng chuẩn"], "answer": 2, "difficulty": "hard"},
    {"question": "Sự kiện 'New Template Detection' được kích hoạt khi nào?", "options": ["Khi Drain3 nhận diện được một file log mới", "Khi một dòng log đi đến leaf của Drain3 nhưng độ tương đồng với mọi template hiện có đều thấp hơn `drain_sim_th`", "Khi người dùng tự định nghĩa một Regex mới", "Khi dung lượng RAM tăng đột ngột"], "answer": 1, "difficulty": "hard"},
    {"question": "Tại sao việc áp dụng 'New Template Detection' ngay sau khi deploy code mới dễ dẫn đến alert fatigue?", "options": ["Vì code mới thường tối ưu hơn", "Vì startup log, health check log mới luôn tạo ra template chưa từng thấy. Cần có grace period để bỏ qua các log này.", "Vì Drain3 cần 24h để train lại", "Do lỗi của hệ điều hành Kubernetes"], "answer": 1, "difficulty": "hard"},
    {"question": "Để nhóm (cluster) các log template có nội dung liên quan (như network lỗi, DB lỗi) khi tham số khác nhau, ta có thể kết hợp Drain3 với thuật toán gì?", "options": ["Isolation Forest", "TF-IDF Vectorizer và Cosine Similarity", "Z-Score", "One-Class SVM"], "answer": 1, "difficulty": "hard"},
    {"question": "Một điểm yếu của kỹ thuật TF-IDF khi so sánh sự tương đồng của hai log template là gì?", "options": ["Không hiểu được Semantic (ngữ nghĩa), ví dụ 'timeout' và 'refused' có thể cùng bản chất mạng nhưng TF-IDF chấm điểm giống nhau rất thấp", "Tốn bộ nhớ không giới hạn", "Không phân biệt được độ dài của template", "Chỉ làm việc với Unstructured log"], "answer": 0, "difficulty": "hard"},
    {"question": "Sentence-Transformers (như MiniLM) khắc phục điểm yếu của TF-IDF bằng cách nào?", "options": ["Biến log thành hình ảnh", "Sinh ra biểu diễn (embedding) dựa trên ngữ nghĩa của cả câu, giúp bắt được mối quan hệ giữa các từ đồng nghĩa/hoàn cảnh", "Nhân đôi kích thước ma trận Sparse", "Chỉ lấy phần tử đầu tiên của câu"], "answer": 1, "difficulty": "hard"},
    
    # Combination & Deep Dives
    {"question": "Với 1TB log/ngày, chiến lược 'Tail-based log sampling' giúp ích như thế nào cho hệ thống AIOps?", "options": ["Chỉ lấy mẫu 10% các log ngẫu nhiên", "Giữ lại 100% log của các request bị lỗi hoặc xử lý rất chậm để phân tích nguyên nhân", "Tăng sampling rate khi có metric anomaly", "Luôn giữ lại phần header của file log"], "answer": 1, "difficulty": "hard"},
    {"question": "Sự khác biệt giữa 'Head-based' và 'Tail-based' sampling là gì?", "options": ["Head-based giữ log phần cứng, Tail-based giữ log phần mềm", "Head-based lấy x% request từ đầu đến cuối; Tail-based chỉ quyết định giữ log sau khi biết request đó bị lỗi hoặc chậm", "Head-based chỉ giữ dòng log đầu, Tail-based giữ dòng cuối", "Không có sự khác biệt về logic cốt lõi"], "answer": 1, "difficulty": "hard"},
    {"question": "Tại sao Adaptive Log Sampling lại được coi là lý tưởng nhất trong AIOps?", "options": ["Code siêu ngắn gọn", "Tốn ít RAM nhất", "Nó tự động tăng tỷ lệ lấy mẫu (Sampling rate) khi Metric Anomaly Detector phát hiện bất thường, giúp giữ lại context sự cố đầy đủ", "Nó thay thế được Isolation Forest"], "answer": 2, "difficulty": "hard"},
    {"question": "Structured Logging (VD: định dạng JSON) giúp thay thế hoàn toàn công đoạn nào trong quy trình phân tích log?", "options": ["Thay thế bước tính TTD", "Thay thế mô hình Isolation Forest", "Thay thế Drain3 (bước Log Parsing) vì dữ liệu đã nằm sẵn trong các Key/Value có thể aggregate ngay lập tức", "Thay thế hoàn toàn Metric gathering"], "answer": 2, "difficulty": "hard"},
    {"question": "Trong thư viện Drain3, tham số `drain_depth` quyết định gì?", "options": ["Số dòng log tối đa được đọc", "Độ sâu tối đa của parse tree, thường từ 3-6. Sâu hơn sẽ chính xác hơn nhưng tốn chi phí duyệt", "Số lượng template tối đa được cấp", "Ngưỡng gộp nhóm similarity"], "answer": 1, "difficulty": "hard"},
    {"question": "KPI 'Grouping accuracy' trong Log Parsing đo lường khả năng gì của Parser?", "options": ["Tỷ lệ nhóm sai log lỗi thành log thường", "Tỷ lệ các dòng log cùng tính chất thực sự được gom vào cùng 1 cụm (cluster) và không bị lẫn log khác loại (F1 score cao)", "Khả năng phát hiện New Template", "Thời gian hoàn thành parse 1 triệu dòng"], "answer": 1, "difficulty": "hard"},
    {"question": "Khi Cross-Signal Analysis tìm thấy một log template (VD: T-042) spike cùng thời điểm với metric latency spike, bước drill-down tiếp theo nên là gì?", "options": ["Xóa template đó khỏi danh sách", "Chạy Autoencoder trên log", "Phân tích phần Parameters (như IP, orderId) của T-042 để thu hẹp vùng lỗi cục bộ (VD: DB nào, user nào đang gặp sự cố)", "Chỉ cần gửi email báo 'T-042' cho dev"], "answer": 2, "difficulty": "hard"},
    {"question": "Tại sao trong kịch bản 'Memory Leak', Z-score có xu hướng 'bị mù' (miss) ở khung giờ thứ 8-12?", "options": ["Vì RAM không bao giờ giảm", "Vì sự tăng tuyến tính nhưng rất chậm khiến giá trị rolling mean và standard deviation tự 'trượt' (drift) theo mức dữ liệu mới, giữ cho Z-score thấp hơn ngưỡng alert", "Bởi vì Z-score mặc định tắt vào ban đêm", "Vì Z-score không thiết kế cho metric memory"], "answer": 1, "difficulty": "hard"},
    {"question": "Vì sao mô hình EWMA (Exponentially Weighted Moving Average) giải quyết được bài toán phát hiện drift mà 3σ thất bại?", "options": ["Vì EWMA dùng Deep Learning", "Vì EWMA 'nhớ' được dữ liệu cũ (dù weight nhỏ), nên trung bình EWMA phản ánh mức độ bình thường dài hạn và không bị drift theo các giá trị tăng chậm", "Vì EWMA không cần dữ liệu lịch sử", "EWMA có thể tính bằng công thức lượng giác"], "answer": 1, "difficulty": "hard"},
    {"question": "Nhược điểm lớn nhất của mô hình Autoencoder khi triển khai trong production là gì?", "options": ["Chạy rất nhanh nhưng hay bị Crash", "Khó giải thích (Black box) cho Ops team về lý do tại sao nó alert, cần GPU để train trên dataset lớn và phải retrain khi hệ thống thay đổi", "Nó không phát hiện được lỗi mạng", "Autoencoder chỉ dùng được trên Log, không dùng được trên Metric"], "answer": 1, "difficulty": "hard"},
    
    # Creating remaining variations to reach 70
    {"question": "Nếu data metric có chu kỳ tuần (weekly seasonal) và độ phân giải 1-hour, ta thiết lập period bằng bao nhiêu cho thuật toán STL?", "options": ["1440", "168", "7", "24"], "answer": 1, "difficulty": "hard"},
    {"question": "Khái niệm 'Alert Fatigue' (mệt mỏi vì cảnh báo) sinh ra từ chỉ số đo lường (KPI) nào thấp kém?", "options": ["Recall quá thấp", "TTD quá lớn", "Precision quá thấp (quá nhiều False Alarms)", "F1 score cao"], "answer": 2, "difficulty": "hard"},
    {"question": "Để tối ưu hàm phân tích Cross-signal, cần sử dụng pandas code nào để biểu diễn Log Count Time Series?", "options": ["pd.melt()", "ts.unstack(fill_value=0) để chuyển rows thời gian và columns là Template ID", "df.dropna()", "ts.fillna()"], "answer": 1, "difficulty": "hard"},
    {"question": "Điều nào KHÔNG PHẢI là nguyên nhân khiến hệ thống log bị phình to lưu lượng (Log volume)?", "options": ["Pod/container Kubernetes sinh suffix random", "Số lượng Microservices bùng nổ", "Unstructured Log có kích thước lớn hơn Structured Log", "Sự xuất hiện của hàng tỷ dòng dữ liệu thay đổi tham số IP, ID"], "answer": 2, "difficulty": "hard"},
    {"question": "Với 5 template liên quan tới lỗi network và 3 template về authentication, việc dùng IF (Isolation Forest) kết hợp với các log này đòi hỏi gì?", "options": ["Khởi tạo mảng n-D chứa tần suất của từng template count theo time window", "Nối chúng thành một chuỗi văn bản dài", "Chỉ đưa số đếm tổng", "Dùng GPU để render text"], "answer": 0, "difficulty": "hard"},
    {"question": "Trong Drain3, thuật ngữ 'Dynamic values' hay Parameter được ký hiệu chung bằng ký tự gì sau khi parse?", "options": ["<*>", "[dyn]", "{var}", "XXX"], "answer": 0, "difficulty": "hard"},
    {"question": "Khi metric báo Error Rate tăng cao, có thể Log sẽ trả về hàng ngàn dòng. Cơ chế nào của Drain3 giúp xác định lỗi mới chưa từng thấy?", "options": ["Similarity Matching", "Return 'New Template' if sim_th is not met at leaf nodes", "Tree Pruning", "Root Length Validation"], "answer": 1, "difficulty": "hard"},
    {"question": "Trong biểu đồ quan hệ Univariate vs Multivariate, trường hợp nào bắt buộc dùng Multivariate (như Isolation Forest)?", "options": ["Khi muốn xem CPU 1 Pod có quá tải hay không", "Khi Error Rate đạt 5%", "Khi các metric lẻ đều ở ngưỡng bình thường nhưng TƯƠNG QUAN (correlation) giữa chúng rất vô lý (VD: Traffic xuống, DB disk IO tăng)", "Khi không có kinh phí mua GPU"], "answer": 2, "difficulty": "hard"},
    {"question": "Kỹ thuật 'iterative reweighting' trong STL `robust=True` có tác dụng gì?", "options": ["Chạy hàm nhiều lần để giảm chi phí RAM", "Trong mỗi lần fit, các điểm nghi ngờ là outlier sẽ bị giảm trọng số ở lần fit tiếp theo, đảm bảo Trend mượt và không bị kéo theo outlier", "Tăng trọng số outlier để bắt dễ hơn", "Tính lại trung bình hàm log"], "answer": 1, "difficulty": "hard"},
    {"question": "Việc sử dụng ACF (Autocorrelation Function) đồ thị hóa để tìm Period trong time series phụ thuộc vào dấu hiệu nào?", "options": ["Màu sắc của các thanh Bar", "Điểm Peak (đỉnh) nổi bật đầu tiên xuất hiện sau điểm lag=0", "Số lượng đường đứt khúc", "Thung lũng thấp nhất"], "answer": 1, "difficulty": "hard"},

    # Generate more until we reach ~70. I will write distinct technical nuances.
    {"question": "Tại sao trong AIOps, người ta khuyên ưu tiên dùng Isolation Forest (IF) hơn One-Class SVM ở môi trường production?", "options": ["Vì SVM chạy chậm ở quy mô data khổng lồ (O(n²) đến O(n³)), tốn công tuning (kernel, nu) và yêu cầu data sạch, trong khi IF nhanh và chịu nhiễu tốt", "Vì IF dùng AI tạo sinh", "Vì IF yêu cầu GPU", "Vì One-Class SVM không hỗ trợ trên Linux"], "answer": 0, "difficulty": "hard"},
    {"question": "Trong Feature Engineering của ML Methods, feature 's.shift(1)' giúp mang lại ngữ cảnh (context) gì?", "options": ["Độ biến thiên tổng thể", "Giá trị của dữ liệu tại 1 thời điểm (lag) ngay trước đó", "Sai số chuẩn", "Trung bình động 1 phút"], "answer": 1, "difficulty": "hard"},
    {"question": "Sự khác biệt cốt lõi giữa Log và Metric trong Observability là gì?", "options": ["Log có dạng số, Metric có dạng chữ", "Metric tốn dung lượng hơn Log", "Metric là các giá trị tổng hợp (aggregated numbers) nhẹ nhưng thiếu chi tiết, Log là sự kiện rời rạc mang dữ liệu nguyên bản và nặng nề", "Metric chỉ xem được bằng Splunk"], "answer": 2, "difficulty": "hard"},
    {"question": "Thuật toán LOESS trong STL Decomposition viết tắt cho điều gì và làm chức năng gì?", "options": ["Log Oriented Error Systems - Kiểm tra log lỗi", "LOcally Estimated Scatterplot Smoothing - Fit nhiều đường cong mượt cục bộ thay vì 1 đường thẳng cứng nhắc", "Long Observability Error Size - Giới hạn kích thước Log", "Linear Object Event - Tạo Event rác"], "answer": 1, "difficulty": "hard"},
    {"question": "Nếu dữ liệu có skewness lớn hơn 1 (heavily skewed), điều gì xảy ra nếu cố chấp sử dụng 3σ (Z-Score)?", "options": ["Mọi thứ vẫn bình thường", "Threshold bên trên quá rộng (miss anomaly), và threshold bên dưới có thể ra số âm vô lý (miss luôn cả lỗi giảm đột ngột)", "Hệ thống tự động dùng Log transform", "Z-Score không tính được std deviation"], "answer": 1, "difficulty": "hard"},
    {"question": "Trong Log Parsing, nếu ta áp dụng kỹ thuật 'Head-based' sampling 10% request, hệ quả rõ nhất là gì?", "options": ["Ta giữ trọn vẹn workflow/chuỗi log của các request đã chọn, nhưng bỏ lỡ 90% lỗi của các request không được chọn", "Ta sẽ bắt được mọi lỗi slow-burn", "Dung lượng log không giảm", "Ta tiết kiệm được 99% không gian lưu trữ"], "answer": 0, "difficulty": "hard"},
    {"question": "Với Isolation Forest, thông số `n_estimators` (số cây) ảnh hưởng ra sao?", "options": ["Nhiều cây hơn làm tăng rủi ro Overfit", "Càng nhiều cây thì mô hình càng chạy chậm nhưng quyết định điểm anomaly càng ổn định (thường 200 là đủ dùng)", "Phải để số cây lớn hơn 1000 mới chính xác", "Càng nhiều cây thì RAM càng giảm"], "answer": 1, "difficulty": "hard"},
    {"question": "Tại sao một hệ thống Service hiện đại lại có hỗn hợp cả Structured và Unstructured Log?", "options": ["Vì lập trình viên thích thế", "Vì dù các service mới viết JSON gọn gàng, hệ thống vẫn phải tương tác với Legacy DB, OS kernel hay 3rd-party lib có thói quen in log plain text", "Do ngôn ngữ Java không hỗ trợ JSON", "Vì Unstructured log bảo mật hơn"], "answer": 1, "difficulty": "hard"},
    {"question": "Mô hình LSTM Autoencoder vượt trội hơn Autoencoder thường ở điểm nào?", "options": ["Tốn ít tài nguyên hơn", "Nó hiểu được tính phụ thuộc theo thời gian (temporal dependency), 'nhớ' bối cảnh thay vì coi mỗi time step là độc lập", "Có thể tự động viết lại code", "Dễ giải thích với Ops team"], "answer": 1, "difficulty": "hard"},
    {"question": "Tại sao trong quy trình chuẩn AIOps, DL (Deep Learning) chỉ được dùng cho <20% use case?", "options": ["Do thiếu thư viện lập trình", "Do DL chậm, tốn data sạch, khó bảo trì (ML Engineer babysit), và quan trọng nhất là Black Box (khó giải thích tại sao alert) cho Ops", "Do DL có độ chính xác quá thấp", "Do DL không hỗ trợ Log parsing"], "answer": 1, "difficulty": "hard"},
    
    # 51 - 70: More mixed tricky questions
    {"question": "Bạn có data độ phân giải 15 phút. Nếu áp dụng STL cho pattern trong 1 ngày, `period` chuẩn là:", "options": ["96", "24", "1440", "60"], "answer": 0, "difficulty": "hard"},
    {"question": "Một New Template được Drain3 phát hiện. Nguyên nhân hợp lý nhất là gì?", "options": ["Ram bị leak dẫn tới OS can thiệp", "Hành vi người dùng tăng nhẹ", "Deploy tính năng mới hoặc Hacker lợi dụng lỗ hổng SQL Injection sinh ra log pattern lạ", "Server bị tắt đột ngột"], "answer": 2, "difficulty": "hard"},
    {"question": "Tại sao IQR (Interquartile Range) lại 'robust' (vững) trước Outlier hơn là Mean/Std (3σ)?", "options": ["Vì IQR dùng Median (giá trị giữa) và Percentile, không bị kéo văng bởi các giá trị quá lớn hay quá nhỏ ở phần đuôi (tail)", "Vì IQR có công thức dài hơn", "Vì IQR dùng Machine Learning", "Vì IQR dùng Log Transform"], "answer": 0, "difficulty": "hard"},
    {"question": "Feature `hour` và `is_weekend` giúp mô hình Isolation Forest (IF) học được điều gì?", "options": ["Phát hiện chu kỳ GC", "Nắm bắt được tính Mùa vụ (Seasonal) thay vì chỉ học giá trị thô, tránh false alarm khi Traffic ban đêm thấp", "Biết được lịch đi làm của người trực (On-call)", "Tính toán Rate of Change tốt hơn"], "answer": 1, "difficulty": "hard"},
    {"question": "Trong EWMA, so với Rolling Mean 3σ, vì sao đường biểu diễn của EWMA ít bị 'drift' bám sát theo sự cố từ từ (slow-burn) hơn?", "options": ["Vì nó có AI", "Do EWMA cộng gộp phần dư vô hạn", "Vì EWMA dùng trọng số suy giảm mũ, phần dữ liệu rất cũ trong lịch sử không bao giờ bị 'quên' hoàn toàn (khác không), nên nó vẫn 'nhớ' baseline gốc", "Vì EWMA chạy bằng GPU nhanh hơn"], "answer": 2, "difficulty": "hard"},
    {"question": "Đặc điểm 'Dynamic Parameter' trong Log (ví dụ [tid:a8f2e1]) gây khó khăn chủ yếu cho việc gì?", "options": ["Khó đọc trên terminal", "Ngăn chặn việc dùng string match đơn giản để Group & Aggregate các thông điệp có cùng bản chất", "Làm cho ổ cứng nhanh hỏng", "Khiến hệ thống không thể lưu JSON"], "answer": 1, "difficulty": "hard"},
    {"question": "Khi TF-IDF Vectorizer nhóm các templates, log 'Disk usage at 90%' và 'Disk failure on sda1' có thể không chung cụm. Vì sao?", "options": ["TF-IDF là AI tạo sinh", "TF-IDF chỉ quan tâm độ phủ của từ (frequency), nó không phân biệt được ý nghĩa Semantic chung của cụm từ 'ổ cứng bị đầy/lỗi'", "Vì hai template này khác ký tự đầu", "Vì Drain3 chặn TF-IDF"], "answer": 1, "difficulty": "hard"},
    {"question": "Sentence-Transformer tính toán sự tương đồng (similarity) của hai câu (template) dựa vào gì?", "options": ["Số lượng từ lặp lại", "Tạo ra không gian Dense Vector (Embedding) và đo Cosine Similarity của các vector mang ngữ nghĩa", "Khoảng cách Levenshtein", "Sử dụng độ sâu của cây Drain3"], "answer": 1, "difficulty": "hard"},
    {"question": "Tại sao trong AIOps, một Metric bị coi là 'Noisy' lại nguy hiểm?", "options": ["Nó làm hỏng loa báo động", "Nó che lấp tín hiệu thật, tạo False Alarms liên tục dẫn đến Alert Fatigue, on-call mất niềm tin và bỏ qua cảnh báo quan trọng", "Nó tốn quá nhiều Log Storage", "Nó làm cho Z-Score âm"], "answer": 1, "difficulty": "hard"},
    {"question": "Để kết hợp Metric và Log hiệu quả, cấu trúc dữ liệu DataFrame lý tưởng sau khi đếm log template trông như thế nào?", "options": ["Một chuỗi JSON cực dài", "Index là Time window (VD mỗi 5p), Column là các Template IDs, Values là số lượng xuất hiện (Counts)", "Index là Template ID, Values là Log Text", "Một List chứa hàng tỷ String"], "answer": 1, "difficulty": "hard"},
    {"question": "Với 3σ, tại vùng 'Seasonal transition' (chuyển giao giữa Peak giờ làm việc và Off-peak ban đêm), điều gì thường xuyên xảy ra?", "options": ["Hệ thống sẽ chạy nhanh gấp đôi", "3σ band chưa kịp điều chỉnh cong theo (vì tính theo trung bình n phút), dẫn đến rất nhiều False Positive (False Alarms)", "Metric latency sẽ bị crash", "Z-score rơi về bằng 0"], "answer": 1, "difficulty": "hard"},
    {"question": "Khi phát hiện một Metric Anomaly, việc Drill down vào top_templates giúp xác định điều gì?", "options": ["Xác suất báo lỗi giả", "Định danh được quy trình nào, user nào, hoặc dependency nào (DB/API) cụ thể sinh ra lỗi", "Lượng RAM đang tiêu hao", "Tính được MTTR"], "answer": 1, "difficulty": "hard"},
    {"question": "Khái niệm 'Unsupervised' trong Isolation Forest mang lại lợi ích thực tiễn gì?", "options": ["Model có thể chạy offline", "Không cần chi phí/ thời gian gán nhãn dữ liệu thủ công (Labeling), có thể train thẳng trên dữ liệu thực tế", "Nó loại bỏ hẳn Outlier", "Nó đảm bảo Precision 100%"], "answer": 1, "difficulty": "hard"},
    {"question": "Tại sao phải cẩn thận khi dùng Log Transform `np.log1p()`?", "options": ["Vì nó tăng skewness", "Nó làm sai lệch phân phối", "Cần đảm bảo dữ liệu không có số âm lớn, và chỉ áp dụng cho dữ liệu Heavily Right-Skewed để kéo đuôi về", "Nó bắt buộc chạy bằng PyTorch"], "answer": 2, "difficulty": "hard"},
    {"question": "Khi sử dụng LSTM Autoencoder, tại sao phải Retrain mô hình khi có Deploy code mới?", "options": ["Vì IP thay đổi", "Vì hệ thống thay đổi sẽ sinh ra các pattern/dependency bình thường mới, mô hình cũ sẽ coi đó là Anomaly dẫn tới ngập lụt Alert", "Vì LSTM bị xóa cache", "Do Isolation Forest yêu cầu"], "answer": 1, "difficulty": "hard"},
    {"question": "Điều nào mô tả đúng nhất quy tắc 'First-pass, Second-pass filter' trong AIOps Detection?", "options": ["Dùng IF bắt rộng, dùng 3σ lọc False alarm", "Dùng 3σ/STL làm first-pass để có Recall cao (không miss lỗi), dùng Isolation Forest làm second-pass để lấy Precision cao (lọc bớt False Alarm)", "Dùng LLM quét 2 lần", "Dùng Log thay cho Metric ở lần quét thứ 2"], "answer": 1, "difficulty": "hard"},
    {"question": "Drain3 đạt Speed O(1) nghĩa là gì?", "options": ["Tốc độ parse không phụ thuộc vào kích thước của dòng log", "Thời gian parse của mỗi dòng log là cố định, không bị chậm đi dù số lượng template hiện có trong hệ thống tăng lên bao nhiêu", "Parse 1 triệu dòng mất đúng 1 giây", "Chạy trên 1 Core CPU"], "answer": 1, "difficulty": "hard"},
    {"question": "Trong bộ dữ liệu có Lag Feature `s.shift(window)`, việc này cung cấp cho Isolation Forest thông tin gì?", "options": ["Thấy được bức tranh quá khứ cách thời điểm hiện tại đúng bằng 1 khoảng window (VD 1 giờ), giúp phát hiện Spike so với baseline", "Tìm ra địa chỉ IP cũ", "Xóa bỏ tính Stationarity", "Kiểm tra xem hệ thống có Restart không"], "answer": 0, "difficulty": "hard"},
    {"question": "Tại sao chi phí Splunk lại tỷ lệ thuận với việc sử dụng Unstructured Log?", "options": ["Vì Splunk ưu tiên JSON", "Splunk thu phí theo GB Ingested, Unstructured Log có thể sinh ra Storage cực lớn do không tối ưu hóa Field/Key so với giải pháp Streaming pipeline tùy chỉnh", "Do Splunk phải dùng LLM parse", "Do Splunk tính phí hiển thị hình ảnh"], "answer": 1, "difficulty": "hard"},
    {"question": "Khi kết hợp Metric (D1) và Log (D2), nếu hệ thống đang dùng 100% Unstructured log thì điều kiện tiên quyết trước khi gộp 2 loại tín hiệu là gì?", "options": ["Phải chạy Isolation Forest trước", "Phải sử dụng Log Parsing (như Drain3) để số hóa text thành Template Counts Time-Series thì mới đối chiếu được với Metric Time-Series", "Bắt buộc đổi sang JSON", "Phải lưu log ở định dạng CSV"], "answer": 1, "difficulty": "hard"},
    
    # 71 - 72: A couple more to be safe (ensure strictly >= 70)
    {"question": "Dấu hiệu dễ nhận biết nhất khi `drain_sim_th` được thiết lập quá cao là gì?", "options": ["Dung lượng file kết quả nhỏ lại", "Hệ thống chỉ tạo 1-2 cluster cho tất cả log", "Khó khăn trong việc tìm ra New Template, số lượng Cluster (Unique Templates) phình to không giới hạn vì mỗi biến nhỏ cũng bị tách ra", "Hệ thống tự văng lỗi 'Overflow'"], "answer": 2, "difficulty": "hard"},
    {"question": "Tại sao khi tính Z-score, ta nên set biến `rolling_std = rolling_std.replace(0, 1e-10)`?", "options": ["Để mô hình chạy mượt hơn", "Vì trong trường hợp Metric hoàn toàn phẳng (đứng im), Standard Deviation = 0 sẽ sinh ra lỗi chia cho 0, làm toàn bộ logic sụp đổ", "Để Z-score nhận giá trị âm", "Đây là yêu cầu của thư viện Pandas"], "answer": 1, "difficulty": "hard"},
]

# Đảm bảo trộn lộn xộn các câu hỏi
random.shuffle(mixed_questions)

gen_quizzes.generate_html("AIOps Quiz - Tổng Hợp Nâng Cao Khó (Metric & Log)", "/home/duckq1u/Documents/Aiops-g4/ôn tập/quiz_mixed.html", mixed_questions)
print(f"Generated quiz_mixed.html with {len(mixed_questions)} questions.")
