import gen_quizzes

q2 = [
    # Easy
    {"question": "Mục đích chính của việc sử dụng log kết hợp với metric là gì?", "options": ["Để lưu trữ dữ liệu vĩnh viễn", "Metric báo 'cái gì sai', log giải thích 'tại sao'", "Để giảm tải cho server", "Để tạo biểu đồ đẹp hơn"], "answer": 1, "difficulty": "easy"},
    {"question": "Trong production, log thường có định dạng nào phổ biến nhất?", "options": ["100% Structured Log (JSON)", "100% Unstructured Log", "Hỗn hợp giữa cả Structured và Unstructured", "Không ghi log"], "answer": 2, "difficulty": "easy"},
    {"question": "Điểm khác biệt lớn nhất giữa log của môi trường textbook và production là gì?", "options": ["Production log có màu sắc", "Production log chứa các tham số động thay đổi liên tục", "Production log luôn bằng tiếng Anh", "Textbook log dài hơn"], "answer": 1, "difficulty": "easy"},
    {"question": "Tại sao việc dùng lệnh `grep` trên hệ thống log lớn không hiệu quả để phân tích anomaly?", "options": ["Grep chạy quá chậm", "Grep làm tốn nhiều RAM", "Grep chỉ tìm chuỗi, không thể đếm sự kiện hay phân biệt pattern một cách hệ thống", "Grep chỉ hỗ trợ tiếng Anh"], "answer": 2, "difficulty": "easy"},
    {"question": "Ưu điểm của Structured Log (như JSON) là gì?", "options": ["Tiết kiệm bộ nhớ lưu trữ", "Dễ parse và dễ query theo từng field cụ thể", "Bảo mật hơn", "Không bị lag mạng"], "answer": 1, "difficulty": "easy"},
    {"question": "Tại sao kích thước lưu trữ của Structured Log thường lớn hơn Unstructured Log khoảng 30%?", "options": ["Do chứa hình ảnh", "Do bị lặp lại các tên field (key) trong mỗi dòng", "Do bị nén kém", "Do dùng font chữ lớn"], "answer": 1, "difficulty": "easy"},
    {"question": "Theo Splunk State of Observability 2024, một enterprise trung bình ingest khoảng bao nhiêu log mỗi ngày?", "options": ["1-5 GB", "10-50 GB", "1-5 TB", "100-500 TB"], "answer": 2, "difficulty": "easy"},
    {"question": "Khái niệm 'Log parsing' được hiểu là gì?", "options": ["Xóa các dòng log bị lỗi", "Biến text thô thành cấu trúc có thể phân tích bằng máy", "Gửi log lên Cloud", "Chuyển log thành đồ thị"], "answer": 1, "difficulty": "easy"},
    {"question": "Trong quá trình log parsing, 'Template' là phần nào của dòng log?", "options": ["Phần tên file chứa log", "Phần nội dung tĩnh (static) của dòng log", "Thời gian ghi log", "Phần mã lỗi hệ thống"], "answer": 1, "difficulty": "easy"},
    {"question": "Trong log parsing, 'Parameter' là phần nào của dòng log?", "options": ["Địa chỉ IP của server", "Phần nội dung động thay đổi theo từng dòng (như IP, OrderID)", "Tham số cấu hình của ứng dụng", "Từ khóa tìm kiếm"], "answer": 1, "difficulty": "easy"},
    {"question": "Parser nào hiện được coi là phổ biến và có tỷ lệ accuracy + speed tốt nhất trong AIOps?", "options": ["Drain3", "Spell", "Lenma", "LLM-based Parser"], "answer": 0, "difficulty": "easy"},
    {"question": "Drain3 là thuật toán log parsing được cài đặt bằng ngôn ngữ nào?", "options": ["Java", "C++", "Python", "Go"], "answer": 2, "difficulty": "easy"},
    {"question": "Độ phức tạp thời gian (Time complexity) của Drain3 để parse một dòng log là bao nhiêu?", "options": ["O(1)", "O(log N)", "O(N)", "O(N^2)"], "answer": 0, "difficulty": "easy"},
    {"question": "Drain3 sử dụng cấu trúc dữ liệu cốt lõi nào để phân nhóm log?", "options": ["Hash Table", "Fixed-depth parse tree", "Linked List", "Binary Search Tree"], "answer": 1, "difficulty": "easy"},
    {"question": "Tại level 1 của Drain3 parse tree, các dòng log được nhóm dựa trên tiêu chí nào?", "options": ["Log level (INFO, ERROR)", "Địa chỉ IP", "Log length (số từ trong dòng log)", "Tên Service"], "answer": 2, "difficulty": "easy"},

    # Medium
    {"question": "Tại level 2 của Drain3 parse tree, tiêu chí phân nhóm thường là gì?", "options": ["Độ dài của log", "Ký tự cuối cùng", "First token (thường là log level như ERROR, INFO)", "Số lượng tham số động"], "answer": 2, "difficulty": "medium"},
    {"question": "Tại level 3+ của Drain3, log được gộp vào template dựa trên nguyên tắc gì?", "options": ["Độ dài chuỗi giống nhau tuyệt đối", "Similarity matching với các template đã biết đạt ngưỡng threshold", "Kiểm tra bằng Regex", "Dùng LLM để đánh giá"], "answer": 1, "difficulty": "medium"},
    {"question": "Tham số `drain_sim_th` trong thư viện Drain3 dùng để làm gì?", "options": ["Số lượng cây trong rừng", "Ngưỡng Similarity (Similarity threshold) quyết định việc gộp hay tách template mới", "Độ sâu tối đa của tree", "Thời gian tối đa để parse"], "answer": 1, "difficulty": "medium"},
    {"question": "Hậu quả của việc thiết lập `drain_sim_th` quá cao (ví dụ: 0.8+) là gì?", "options": ["Gộp tất cả log vào 1 template", "Chạy rất nhanh nhưng không chính xác", "Tách quá nhiều, biến mỗi dòng log thành 1 template riêng vô dụng", "Làm treo hệ thống"], "answer": 2, "difficulty": "medium"},
    {"question": "Khi so sánh với Drain3, parser Spell có đặc điểm gì về tốc độ?", "options": ["Nhanh gấp đôi Drain3", "Nhanh bằng Drain3", "Chậm hơn Drain3 từ 5-10 lần", "Chậm hơn cả LLM"], "answer": 2, "difficulty": "medium"},
    {"question": "Nhược điểm chí mạng khiến LLM-based parser (như GPT) chưa thể dùng real-time trên lượng log lớn là gì?", "options": ["Không hiểu được ngữ nghĩa", "Tốc độ quá chậm và tốn kém chi phí API cho từng dòng log", "Không hỗ trợ format JSON", "Hay bị halucinate log level"], "answer": 1, "difficulty": "medium"},
    {"question": "Sau khi log đã được parse thành template, làm thế nào để detect anomaly trên log?", "options": ["Dùng lệnh grep để đếm", "Biến template count thành time series và áp dụng các detector như 3σ hoặc Isolation Forest", "Đọc thủ công", "So sánh kích thước file log"], "answer": 1, "difficulty": "medium"},
    {"question": "Trong AIOps, tại sao 'New Template Detection' lại là một signal cảnh báo rất mạnh?", "options": ["Vì file cấu hình vừa được lưu", "Vì template mới chứng tỏ có một hành vi, lỗi hoặc sự kiện chưa từng xảy ra trong hệ thống", "Vì nó làm tốn RAM", "Vì template mới có màu đỏ"], "answer": 1, "difficulty": "medium"},
    {"question": "Một sai lầm phổ biến khi áp dụng 'New Template Detection' là gì?", "options": ["Không dùng Regex", "Lưu template vào Database", "Không filter template mới trong grace period (1 giờ đầu) ngay sau khi deploy code mới", "Dùng Drain3 thay vì Spell"], "answer": 2, "difficulty": "medium"},
    {"question": "Kỹ thuật TF-IDF tạo vector từ log template dựa trên yếu tố nào?", "options": ["Tần suất xuất hiện của các từ (Word frequency)", "Thứ tự thời gian của từ", "Độ dài của từ", "Cấu trúc ngữ pháp"], "answer": 0, "difficulty": "medium"},
    {"question": "Hạn chế chính của TF-IDF khi dùng để so sánh sự tương đồng của các log template là gì?", "options": ["Chi phí API cao", "Có thể cho similarity thấp nếu các từ khác nhau dù ý nghĩa giống nhau", "Chỉ hỗ trợ tiếng Anh", "Không chạy được trên Python"], "answer": 1, "difficulty": "medium"},
    {"question": "Công nghệ nào thường được sử dụng để hiểu sâu về mặt ngữ nghĩa (semantic) của các log template?", "options": ["Z-Score", "TF-IDF Vectorizer", "Sentence-Transformers (như MiniLM)", "Isolation Forest"], "answer": 2, "difficulty": "medium"},
    {"question": "Cross-Signal Analysis là quá trình kết hợp các thành phần nào để phân tích?", "options": ["Log của DB và Log của App", "Metric anomaly và Log template analysis", "CPU và RAM", "Frontend và Backend"], "answer": 1, "difficulty": "medium"},
    {"question": "Bước đầu tiên trong workflow chuẩn của Cross-Signal Analysis là gì?", "options": ["Parse 100% log", "Đợi Metric anomaly detector trigger để biết thời điểm xảy ra sự cố", "Train mô hình NLP", "Chạy lệnh grep tìm ERROR"], "answer": 1, "difficulty": "medium"},
    {"question": "Tại sao phải filter log trong time window (±5 phút) xung quanh thời điểm metric anomaly?", "options": ["Để làm đẹp biểu đồ", "Để giảm kích thước tập tin", "Để thu hẹp lượng log cần phân tích xuống mức có thể quản lý và tìm ra nguyên nhân", "Để tuân thủ SLA"], "answer": 2, "difficulty": "medium"},
    
    # Hard
    {"question": "Đối với hệ thống gen log tới quy mô 10TB/ngày, kỹ thuật nào bắt buộc phải triển khai ở tầng pipeline?", "options": ["Chạy LLM parser", "Log Sampling (lấy mẫu log)", "Grep toàn bộ hệ thống", "Chuyển hết sang Unstructured Log"], "answer": 1, "difficulty": "hard"},
    {"question": "Tail-based log sampling là chiến lược giữ lại log theo cách nào?", "options": ["Lấy random 10% log", "Lấy 100% log nhưng chỉ của 10% request", "Chỉ giữ lại log từ những request bị lỗi hoặc xử lý chậm", "Tự động tăng sampling khi có lỗi"], "answer": 2, "difficulty": "hard"},
    {"question": "Nhược điểm của Tail-based sampling là gì?", "options": ["Khó code", "Làm mất log của request chậm", "Bỏ lỡ các vấn đề dạng slow-burn (tăng dần chậm) vì nó không lập tức bị gắn cờ lỗi", "Tốn quá nhiều dung lượng"], "answer": 2, "difficulty": "hard"},
    {"question": "Nếu team dev có thể thay đổi source code của service, best practice cho logging để hỗ trợ AIOps là gì?", "options": ["Viết log tiếng Việt", "Sử dụng Structured Logging (JSON) và định nghĩa trước các fields", "Không viết log nữa để giảm tải", "Viết một câu văn thật dài và chi tiết"], "answer": 1, "difficulty": "hard"},
    {"question": "Nếu hệ thống 100% là Structured Log (JSON), bạn có cần dùng thư viện như Drain3 không?", "options": ["Bắt buộc phải dùng", "Không, vì có thể trực tiếp aggregate và detect anomaly trên các trường dữ liệu JSON", "Chỉ dùng khi log là JSON quá lớn", "Dùng để nén JSON"], "answer": 1, "difficulty": "hard"},
    {"question": "Làm thế nào xác định được log template liên quan nhất khi có một metric anomaly xảy ra?", "options": ["Lấy template có chữ ERROR", "Tìm template count nào spike (tăng đột biến) cùng thời điểm với metric anomaly", "Lấy template dài nhất", "Lấy template của DB"], "answer": 1, "difficulty": "hard"},
    {"question": "Lợi thế lớn nhất của chiến lược Adaptive log sampling là gì?", "options": ["Code cực kỳ đơn giản", "Tốn ít bộ nhớ nhất", "Tự động tăng tỷ lệ lấy mẫu (sampling rate) khi phát hiện có anomaly, giữ nguyên context sự cố", "Hỗ trợ nén dung lượng cao nhất"], "answer": 2, "difficulty": "hard"},
    {"question": "Trong đánh giá parser, KPI 'Parsing accuracy' đo lường điều gì?", "options": ["Thời gian parse một dòng log", "Tỷ lệ template được extract chính xác (đúng template/tổng log) so với ground truth", "Số lượng template tạo ra", "Phần trăm log bị vứt bỏ"], "answer": 1, "difficulty": "hard"},
    {"question": "Đối với một service trung bình, số lượng unique templates (Template count) mong đợi rơi vào khoảng nào?", "options": ["1-5", "100-500", "5,000-10,000", "> 1 triệu"], "answer": 1, "difficulty": "hard"},
    {"question": "Nếu số lượng unique templates lên tới 50,000 cho một service đơn giản, vấn đề có khả năng là gì?", "options": ["Service có quá nhiều chức năng", "`drain_sim_th` đặt quá cao dẫn đến tách quá nhiều template không cần thiết", "Server bị tấn công", "Ổ cứng bị đầy"], "answer": 1, "difficulty": "hard"},
    {"question": "Trong thuật toán Drain3, nếu một dòng log đi tới leaf node mà không có template nào vượt qua similarity threshold thì điều gì xảy ra?", "options": ["Dòng log bị bỏ qua", "Chương trình văng lỗi", "Drain3 tạo ra một template mới cho dòng log đó", "Nó được gộp vào template gần nhất dù không đạt ngưỡng"], "answer": 2, "difficulty": "hard"},
    {"question": "Tại sao các parser dựa trên Regex (Regex parser) lại khó scale trong môi trường Enterprise?", "options": ["Vì Regex quá chậm", "Vì nó phụ thuộc vào việc kỹ sư phải viết và bảo trì regex thủ công cho hàng nghìn format thay đổi liên tục", "Vì Regex không chạy được trên Python", "Vì Regex tốn RAM"], "answer": 1, "difficulty": "hard"},
    {"question": "Trong đoạn mã pandas xử lý template timeseries, mục đích của lệnh `ts.unstack(fill_value=0)` là gì?", "options": ["Gỡ bỏ các cột trùng lặp", "Xóa các hàng có giá trị rỗng", "Pivot dữ liệu: chuyển dòng thành cột (mỗi cột là 1 template) và điền 0 cho thời điểm template không xuất hiện", "Nhân đôi dữ liệu"], "answer": 2, "difficulty": "hard"},
    {"question": "Dataset nào trong giới học thuật thường được sử dụng làm benchmark đánh giá độ chính xác của log parsing?", "options": ["ImageNet", "Loghub datasets (HDFS, BGL, Spark...)", "Titanic dataset", "MNIST"], "answer": 1, "difficulty": "hard"},
    {"question": "Trong quá trình tìm root cause qua log, việc trích xuất được Parameters (ví dụ IP, orderId) giúp ích gì?", "options": ["Chỉ để tiết kiệm log storage", "Để làm cho log dễ đọc hơn với người dùng bình thường", "Giúp xác định chính xác đối tượng, server cụ thể hoặc request cụ thể nào đang gặp sự cố", "Để đào tạo mô hình LLM"], "answer": 2, "difficulty": "hard"}
]

gen_quizzes.generate_html("AIOps Quiz - Tuần 1: Log Mining & Parsing", "/home/duckq1u/Documents/Aiops-g4/ôn tập/quiz_w1d2.html", q2)
print("Generated quiz_w1d2.html")
